//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CensusGoods.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoContainer
    {
        public int id { get; set; }
        public int idContainer { get; set; }
        public int idProduct { get; set; }
        public string QuantityProduct { get; set; }
        public string CargoWeight { get; set; }
        public System.DateTime dateStart { get; set; }
        public bool available { get; set; }
    
        public virtual Container Container { get; set; }
        public virtual Product Product { get; set; }
    }
}
