//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CensusGoods.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int id { get; set; }
        public int infoContainer { get; set; }
        public int idCompany { get; set; }
        public int idTariff { get; set; }
        public bool delay { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Container Container { get; set; }
        public virtual Tariff Tariff { get; set; }
    }
}
