//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CensusGoods.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vm_TotalReceipt
    {
        public string Название_контейнера { get; set; }
        public string Название_компании { get; set; }
        public string Тариф { get; set; }
        public string Скидка_компании { get; set; }
        public Nullable<bool> Задолжность { get; set; }
    }
}
